name: Amrita Mazumdar
author: Amrita Mazumdar
url: https://homes.cs.washington.edu/~amrita/
baseurl: /~amrita
twitter: '@amritamaz'
email: 'amrita@cs.washington.edu'
ghrepo: https://github.com/amritamaz/home


markdown: kramdown
highlighter: pygments
# permalink: /:title.html
timezone: America/Seattle
exclude: [README.md, Makefile]


defaults:
    -
        scope:
            path: ""
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post

navigation:
  - title: home
    link: /
  - title: cv
    link: /web-cv.html

